language: node_js
node_js:
  - "6"
  - "5.5.0"
  - "4.2.1"
  - "0.10"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install leaflet@^0.7.7 togeojson@^0.14.0
  - npm install

script:
  - "npm test"